// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMP.Repository.Models;

public partial class BlogPost
{
    public int BlogPostId { get; set; }

    public string Image { get; set; }

    public int DoctorId { get; set; }

    public string PostTitle { get; set; }

    public string PostContent { get; set; }

    public DateTime CreatedDate { get; set; }

    public int? Viewers { get; set; }

    public string Status { get; set; }

    public virtual Doctor Doctor { get; set; }
}