// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMP.Repository.Models;

public partial class Doctor
{
    public int DoctorId { get; set; }

    public string AvatarImage { get; set; }

    public string FullName { get; set; }

    public int YearOfBirth { get; set; }

    public string PhoneNumber { get; set; }

    public string Gender { get; set; }

    public string Address { get; set; }

    public string Degree { get; set; }

    public double? AverageScore { get; set; }

    public string Status { get; set; }

    public virtual ICollection<BlogPost> BlogPosts { get; set; } = new List<BlogPost>();

    public virtual DoctorExpertField DoctorExpertField { get; set; }

    public virtual User DoctorNavigation { get; set; }

    public virtual DoctorSchedule DoctorSchedule { get; set; }

    public virtual ICollection<TreatmentBooking> TreatmentBookings { get; set; } = new List<TreatmentBooking>();
}