// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMP.Repository.Models;

public partial class DoctorExpertField
{
    public int DoctorId { get; set; }

    public int ExpertFieldId { get; set; }

    public virtual Doctor Doctor { get; set; }

    public virtual ExpertField ExpertField { get; set; }
}