// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMP.Repository.Models;

public partial class Feedback
{
    public int PatientId { get; set; }

    public int BookingId { get; set; }

    public int TreatmentId { get; set; }

    public double Score { get; set; }

    public string Comment { get; set; }

    public DateTime CreateDate { get; set; }

    public virtual TreatmentBooking Booking { get; set; }
}