// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMP.Repository.Models;

public partial class Patient
{
    public int PatientId { get; set; }

    public string FullName { get; set; }

    public DateOnly DateOfBirth { get; set; }

    public string Gender { get; set; }

    public string PhoneNumber { get; set; }

    public string Address { get; set; }

    public virtual User PatientNavigation { get; set; }

    public virtual ICollection<TreatmentBooking> TreatmentBookings { get; set; } = new List<TreatmentBooking>();

    public virtual ICollection<TreatmentRecord> TreatmentRecords { get; set; } = new List<TreatmentRecord>();
}