// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMP.Repository.Models;

public partial class StepDetail
{
    public int StepId { get; set; }

    public int AppointmentId { get; set; }

    public string Description { get; set; }

    public string Status { get; set; }

    public virtual Appointment Appointment { get; set; }

    public virtual TreatmentStep Step { get; set; }
}