// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMP.Repository.Models;

public partial class TreatmentStep
{
    public int StepId { get; set; }

    public int TreatmentId { get; set; }

    public string Description { get; set; }

    public virtual StepDetail StepDetail { get; set; }

    public virtual Treatment Treatment { get; set; }
}