// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMP.Repository.Models;

public partial class Treatment
{
    public int TreatmentId { get; set; }

    public string TreatmentName { get; set; }

    public string Description { get; set; }

    public double? RatingScore { get; set; }

    public string Image { get; set; }

    public int? ExpertFieldId { get; set; }

    public virtual ExpertField ExpertField { get; set; }

    public virtual ICollection<TreatmentBooking> TreatmentBookings { get; set; } = new List<TreatmentBooking>();

    public virtual ICollection<TreatmentStep> TreatmentSteps { get; set; } = new List<TreatmentStep>();
}