// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMP.Repository.Models;

public partial class TreatmentBooking
{
    public int BookingId { get; set; }

    public int PatientId { get; set; }

    public int DoctorId { get; set; }

    public int TreatmentId { get; set; }

    public string Status { get; set; }

    public DateOnly? CreatedDate { get; set; }

    public virtual ICollection<Appointment> Appointments { get; set; } = new List<Appointment>();

    public virtual Doctor Doctor { get; set; }

    public virtual ICollection<Feedback> Feedbacks { get; set; } = new List<Feedback>();

    public virtual Patient Patient { get; set; }

    public virtual Treatment Treatment { get; set; }

    public virtual ICollection<TreatmentRecord> TreatmentRecords { get; set; } = new List<TreatmentRecord>();
}