// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMP.Repository.Models;

public partial class TreatmentRecord
{
    public int PatientId { get; set; }

    public int BookingId { get; set; }

    public DateOnly StartDate { get; set; }

    public DateOnly? EndDate { get; set; }

    public virtual TreatmentBooking Booking { get; set; }

    public virtual Patient Patient { get; set; }
}