// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMP.Repository.Models;

public partial class User
{
    public int UserId { get; set; }

    public string Email { get; set; }

    public string Password { get; set; }

    public string RefreshToken { get; set; }

    public DateTime? RefreshTokenExpirity { get; set; }

    public DateTime CreatedDate { get; set; }

    public int RoleId { get; set; }

    public bool IsActive { get; set; }

    public virtual Doctor Doctor { get; set; }

    public virtual Patient Patient { get; set; }

    public virtual Role Role { get; set; }
}